### ISSUE TITLE
cargo shuttle run not working

### ISSUE THREAD

**Issue by dhrubrawat66** [TylerBloom/shuttle-fullstack-rust-example#1]
i create the project by using -->cargo shuttle init --from TylerBloom/shuttle-fullstack-rust-example
then follow the step as explained. when i ran command -->cargo shuttle run, this throw following error
![Screenshot 2024-02-10 090631](https://github.com/TylerBloom/shuttle-fullstack-rust-example/assets/85351405/39c9f39f-c6fb-4d90-979f-90ec98d34003)

**Comment by TylerBloom** [comment]
Hey, thanks for this! I'm working on an update currently. The way that I do fullstack development has changed somewhat, so the update will include those changes too. This should be updated within the hour.

**Comment by TylerBloom** [comment]
@dhrubrawat66 , I've pushed an update. Everything should work now. If you have any other questions or considers, open another issue or reopen this one. Thanks for you help!
